-- DECODING HCM — PRODUCTION SCHEMA
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TABLE IF NOT EXISTS profiles(id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,full_name TEXT NOT NULL,role TEXT DEFAULT 'candidate' CHECK(role IN('candidate','admin')),email TEXT,phone TEXT,phone_verified BOOLEAN DEFAULT false,created_at TIMESTAMPTZ DEFAULT now() NOT NULL,updated_at TIMESTAMPTZ DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS folders(id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),name TEXT NOT NULL UNIQUE,description TEXT DEFAULT '',sort_order INT DEFAULT 0,active BOOLEAN DEFAULT true,created_at TIMESTAMPTZ DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS tests(id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),folder_id UUID REFERENCES folders(id) ON DELETE SET NULL,title TEXT NOT NULL,language TEXT NOT NULL CHECK(language IN('English','Hindi')),passage TEXT NOT NULL,mode TEXT DEFAULT 'screen' CHECK(mode IN('screen','page')),duration_minutes INT DEFAULT 10 CHECK(duration_minutes BETWEEN 1 AND 180),target_wpm NUMERIC(6,2) DEFAULT 35,min_accuracy NUMERIC(5,2),free_error_pct NUMERIC(5,4) DEFAULT .05,penalty_per_error INT DEFAULT 10,allow_backspace BOOLEAN DEFAULT false,leaderboard_enabled BOOLEAN DEFAULT true,active BOOLEAN DEFAULT true,created_at TIMESTAMPTZ DEFAULT now() NOT NULL,updated_at TIMESTAMPTZ DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS attempts(id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,candidate_name TEXT NOT NULL,candidate_id TEXT,test_id UUID REFERENCES tests(id) ON DELETE CASCADE,language TEXT NOT NULL,mode TEXT NOT NULL,duration_seconds INT NOT NULL,typed_words INT NOT NULL,typed_characters INT NOT NULL,correct_characters INT NOT NULL,incorrect_characters INT NOT NULL,total_errors INT NOT NULL,free_errors INT NOT NULL,excess_errors INT NOT NULL,penalty_words INT NOT NULL,gross_wpm NUMERIC(6,2) NOT NULL,net_wpm NUMERIC(6,2) NOT NULL,accuracy NUMERIC(5,2) NOT NULL,suspicious_events JSONB DEFAULT '[]'::jsonb,typed_content TEXT,result_snapshot JSONB,created_at TIMESTAMPTZ DEFAULT now() NOT NULL);
CREATE INDEX IF NOT EXISTS idx_attempts_user_date ON attempts(user_id,created_at DESC);CREATE INDEX IF NOT EXISTS idx_attempts_net_wpm ON attempts(net_wpm DESC);CREATE INDEX IF NOT EXISTS idx_tests_folder_active ON tests(folder_id,active);
CREATE OR REPLACE FUNCTION public.handle_new_user() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN INSERT INTO public.profiles(id,full_name,email,phone,phone_verified) VALUES(NEW.id,COALESCE(NULLIF(NEW.raw_user_meta_data->>'full_name',''),'Candidate'),NEW.email,NEW.raw_user_meta_data->>'phone',false) ON CONFLICT(id) DO UPDATE SET full_name=EXCLUDED.full_name,email=EXCLUDED.email,phone=COALESCE(EXCLUDED.phone,profiles.phone); RETURN NEW; END; $$;
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
CREATE OR REPLACE FUNCTION public.touch_updated_at() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN NEW.updated_at=now();RETURN NEW;END;$$;
DROP TRIGGER IF EXISTS profiles_touch ON profiles;CREATE TRIGGER profiles_touch BEFORE UPDATE ON profiles FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();
DROP TRIGGER IF EXISTS tests_touch ON tests;CREATE TRIGGER tests_touch BEFORE UPDATE ON tests FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();
